export const ACTION_INCREASE = 'ACTION_INCREASE'
export const ACTION_DECREASE = 'ACTION_DECREASE'

//products
export const ACTION_BEGIN_INSERT_PRODUCT = "ACTION_BEGIN_INSERT_PRODUCT"
export const ACTION_INSERT_PRODUCT_SUCCESS = "ACTION_INSERT_PRODUCT_SUCCESS"
export const ACTION_INSERT_PRODUCT_FAILED = "ACTION_INSERT_PRODUCT_FAILED"
export const ACTION_DELETE_PRODUCT = "ACTION_DELETE_PRODUCT"

