export const ACTION_INCREASE = 'ACTION_INCREASE'
export const ACTION_DECREASE = 'ACTION_DECREASE'
//products
export const ACTION_CRUD_TYPE = 'ACTION_CRUD_TYPE'

export const ACTION_BEGIN_FETCH = "ACTION_INSERT_PRODUCT"
export const ACTION_FETCH_SUCCESS = "ACTION_FETCH_SUCCESS"
export const ACTION_FETCH_FAILED = "ACTION_FETCH_FAILED"
