export const ACTION_INCREASE = 'ACTION_INCREASE'
export const ACTION_DECREASE = 'ACTION_DECREASE'

//products
export const ACTION_BEGIN_INSERT_PRODUCT = "ACTION_BEGIN_INSERT_PRODUCT"
export const ACTION_INSERT_PRODUCT_SUCCESS = "ACTION_INSERT_PRODUCT_SUCCESS"
export const ACTION_INSERT_PRODUCT_FAILED = "ACTION_INSERT_PRODUCT_FAILED"

export const ACTION_QUERY_PRODUCT_SUCCESS = "ACTION_QUERY_PRODUCT_SUCCESS"
export const ACTION_QUERY_PRODUCT_FAILED = "ACTION_QUERY_PRODUCT_FAILED"

export const ACTION_BEGIN_UPDATE_PRODUCT = "ACTION_BEGIN_UPDATE_PRODUCT"
export const ACTION_UPDATE_PRODUCT_SUCCESS = "ACTION_UPDATE_PRODUCT_SUCCESS"
export const ACTION_UPDATE_PRODUCT_FAILED = "ACTION_UPDATE_PRODUCT_FAILED"

export const ACTION_BEGIN_DELETE_PRODUCT = "ACTION_BEGIN_DELETE_PRODUCT"
export const ACTION_DELETE_PRODUCT_SUCCESS = "ACTION_DELETE_PRODUCT_SUCCESS"
export const ACTION_DELETE_PRODUCT_FAILED = "ACTION_DELETE_PRODUCT_FAILED"    


